version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - 2181:2181
  kafka:
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:4.1.0
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - 9092:9092
  postgres:
    image: postgres:9.5.3
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: commander
      POSTGRES_PASSWORD: TFgvT3Pb3bWEhXKAfgMk63bo
      POSTGRES_DB: commander
  users:
    depends_on:
      - kafka
    build:
      context: services/users
    environment:
      KAFKA_HOST: kafka:9092
      KAFKA_GROUP: users
  webservice:
    depends_on:
      - kafka
    build:
      context: webservice
    ports:
      - "8080:8080"
    environment:
      KAFKA_HOST: kafka:9092
      KAFKA_GROUP: webservice
  materializer:
    depends_on:
      - kafka
    build:
      context: materializer
    environment:
      KAFKA_HOST: kafka:9092
      KAFKA_GROUP: materializer
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: commander
      POSTGRES_PASSWORD: TFgvT3Pb3bWEhXKAfgMk63bo
      POSTGRES_DB: commander
volumes:
  zookeeper:
  kafka:
  postgres:
